### ISSUE TITLE
Unity Crash

### ISSUE THREAD

**Issue by oykuyilmaz** [VisionerTech/PTAM_UNITY#2]
I have got two endoscope cameras and wanted to try your project with them. I've succesfully built the dll and calibrated cameras. However, when I try to run unity project, it crashes and gets close. What could be the reason, could you help me?

**Comment by flankechen** [comment]
@oykuyilmaz to use other camera setups, you have to calibrate your camera first, https://github.com/VisionerTech/stereo_calib. changing the files in /save_param/ folder to yours. the  PTAM_UNITY/UnityProject/camera.cfg is the camera model used by PTAM tracking, 2 parameters focal, 2 parameters image center, in units of image width / height respectively. So yes if you have a 640×480 image and you want the equivalent focal length / center in pixels, multiply params[0] & params[2] by 640, params[1] & params[3] by 480.
some of the codes in this project is hardcoded to 1080*1080 resolution, make them yours in the code.
